// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

// Protobuf Java Version: 4.26.1
package org.thxnet.core.hello.v0;

public interface Hello1ResposneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thxnet.core.hello.v0.Hello1Resposne)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional string more_message = 2;</code>
   * @return Whether the moreMessage field is set.
   */
  boolean hasMoreMessage();
  /**
   * <code>optional string more_message = 2;</code>
   * @return The moreMessage.
   */
  java.lang.String getMoreMessage();
  /**
   * <code>optional string more_message = 2;</code>
   * @return The bytes for moreMessage.
   */
  com.google.protobuf.ByteString
      getMoreMessageBytes();
}
