// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

// Protobuf Java Version: 4.26.1
package org.thxnet.core.hello.v0;

public interface Hello1RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thxnet.core.hello.v0.Hello1Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string nick_name = 2;</code>
   * @return Whether the nickName field is set.
   */
  boolean hasNickName();
  /**
   * <code>optional string nick_name = 2;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <code>optional string nick_name = 2;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();
}
