// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

// Protobuf Java Version: 4.26.1
package org.thxnet.core.hello.v0;

/**
 * Protobuf type {@code thxnet.core.hello.v0.Hello1Resposne}
 */
public final class Hello1Resposne extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:thxnet.core.hello.v0.Hello1Resposne)
    Hello1ResposneOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Hello1Resposne.class.getName());
  }
  // Use Hello1Resposne.newBuilder() to construct.
  private Hello1Resposne(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Hello1Resposne() {
    message_ = "";
    moreMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.thxnet.core.hello.v0.HelloProto.internal_static_thxnet_core_hello_v0_Hello1Resposne_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.thxnet.core.hello.v0.HelloProto.internal_static_thxnet_core_hello_v0_Hello1Resposne_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.thxnet.core.hello.v0.Hello1Resposne.class, org.thxnet.core.hello.v0.Hello1Resposne.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MORE_MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object moreMessage_ = "";
  /**
   * <code>optional string more_message = 2;</code>
   * @return Whether the moreMessage field is set.
   */
  @java.lang.Override
  public boolean hasMoreMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string more_message = 2;</code>
   * @return The moreMessage.
   */
  @java.lang.Override
  public java.lang.String getMoreMessage() {
    java.lang.Object ref = moreMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      moreMessage_ = s;
      return s;
    }
  }
  /**
   * <code>optional string more_message = 2;</code>
   * @return The bytes for moreMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMoreMessageBytes() {
    java.lang.Object ref = moreMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      moreMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, message_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, moreMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, message_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, moreMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.thxnet.core.hello.v0.Hello1Resposne)) {
      return super.equals(obj);
    }
    org.thxnet.core.hello.v0.Hello1Resposne other = (org.thxnet.core.hello.v0.Hello1Resposne) obj;

    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasMoreMessage() != other.hasMoreMessage()) return false;
    if (hasMoreMessage()) {
      if (!getMoreMessage()
          .equals(other.getMoreMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasMoreMessage()) {
      hash = (37 * hash) + MORE_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMoreMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.thxnet.core.hello.v0.Hello1Resposne parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.thxnet.core.hello.v0.Hello1Resposne parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.thxnet.core.hello.v0.Hello1Resposne parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.thxnet.core.hello.v0.Hello1Resposne prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code thxnet.core.hello.v0.Hello1Resposne}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:thxnet.core.hello.v0.Hello1Resposne)
      org.thxnet.core.hello.v0.Hello1ResposneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.thxnet.core.hello.v0.HelloProto.internal_static_thxnet_core_hello_v0_Hello1Resposne_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.thxnet.core.hello.v0.HelloProto.internal_static_thxnet_core_hello_v0_Hello1Resposne_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.thxnet.core.hello.v0.Hello1Resposne.class, org.thxnet.core.hello.v0.Hello1Resposne.Builder.class);
    }

    // Construct using org.thxnet.core.hello.v0.Hello1Resposne.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = "";
      moreMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.thxnet.core.hello.v0.HelloProto.internal_static_thxnet_core_hello_v0_Hello1Resposne_descriptor;
    }

    @java.lang.Override
    public org.thxnet.core.hello.v0.Hello1Resposne getDefaultInstanceForType() {
      return org.thxnet.core.hello.v0.Hello1Resposne.getDefaultInstance();
    }

    @java.lang.Override
    public org.thxnet.core.hello.v0.Hello1Resposne build() {
      org.thxnet.core.hello.v0.Hello1Resposne result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.thxnet.core.hello.v0.Hello1Resposne buildPartial() {
      org.thxnet.core.hello.v0.Hello1Resposne result = new org.thxnet.core.hello.v0.Hello1Resposne(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.thxnet.core.hello.v0.Hello1Resposne result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = message_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.moreMessage_ = moreMessage_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.thxnet.core.hello.v0.Hello1Resposne) {
        return mergeFrom((org.thxnet.core.hello.v0.Hello1Resposne)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.thxnet.core.hello.v0.Hello1Resposne other) {
      if (other == org.thxnet.core.hello.v0.Hello1Resposne.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMoreMessage()) {
        moreMessage_ = other.moreMessage_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              moreMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 1;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 1;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 1;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object moreMessage_ = "";
    /**
     * <code>optional string more_message = 2;</code>
     * @return Whether the moreMessage field is set.
     */
    public boolean hasMoreMessage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string more_message = 2;</code>
     * @return The moreMessage.
     */
    public java.lang.String getMoreMessage() {
      java.lang.Object ref = moreMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moreMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string more_message = 2;</code>
     * @return The bytes for moreMessage.
     */
    public com.google.protobuf.ByteString
        getMoreMessageBytes() {
      java.lang.Object ref = moreMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moreMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string more_message = 2;</code>
     * @param value The moreMessage to set.
     * @return This builder for chaining.
     */
    public Builder setMoreMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      moreMessage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string more_message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoreMessage() {
      moreMessage_ = getDefaultInstance().getMoreMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string more_message = 2;</code>
     * @param value The bytes for moreMessage to set.
     * @return This builder for chaining.
     */
    public Builder setMoreMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      moreMessage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:thxnet.core.hello.v0.Hello1Resposne)
  }

  // @@protoc_insertion_point(class_scope:thxnet.core.hello.v0.Hello1Resposne)
  private static final org.thxnet.core.hello.v0.Hello1Resposne DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.thxnet.core.hello.v0.Hello1Resposne();
  }

  public static org.thxnet.core.hello.v0.Hello1Resposne getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Hello1Resposne>
      PARSER = new com.google.protobuf.AbstractParser<Hello1Resposne>() {
    @java.lang.Override
    public Hello1Resposne parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Hello1Resposne> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Hello1Resposne> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.thxnet.core.hello.v0.Hello1Resposne getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

